language: cpp
sudo: required
dist: trusty
services:
  - docker
matrix:
  include:
    - os: linux
      env: ARCH="x86_64" DOCKER_IMAGE="staticfloat/julia_workerbase:centos6_9-x64" JULIA_URL="https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz"
    - os: osx
      env: ARCH="x86_64" JULIA_URL="https://julialangnightlies-s3.julialang.org/bin/osx/x64/julia-latest-osx.dmg"
      osx_image: xcode8
notifications:
  email: false
before_script:
  - if [ "$(uname)" = "Linux" ]; then
      docker pull $DOCKER_IMAGE;
    fi
  - export CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
  - if [ "$(uname)" = "Linux" ]; then
      mkdir -p ~/julia;
      curl -A "${CURL_USER_AGENT}" -s -L --retry 7 "${JULIA_URL}" | tar -C ~/julia -x -z --strip-components=1 -f -;
    fi
  - if [ "$(uname)" = "Darwin" ]; then
      curl -A "${CURL_USER_AGENT}" -s -L --retry 7 -o julia.dmg "${JULIA_URL}";
      mkdir juliamnt;
      hdiutil mount -readonly -mountpoint juliamnt julia.dmg;
      cp -a juliamnt/*.app/Contents/Resources/julia ~/;
    fi
  - export PATH="${PATH}:${HOME}/julia/bin"
  - julia -e 'versioninfo()'
script:
  - if [ "$(uname)" = "Linux" ]; then
      docker run --user=$(id -u):$(id -g) -ti -v $(pwd):/src -w /src $DOCKER_IMAGE make;
    else
      make;
    fi
  - julia test.jl
before_deploy:
  - cd build/lib && ls -p | grep -v / | xargs tar -cvf ../../libfftw-$(cat VERSION)-$TRAVIS_OS_NAME-$ARCH.tar.gz
deploy:
  provider: releases
  api_key:
    secure: "$GH_API_TOKEN"
  file_glob: true
  file: "libfftw-*.tar.gz"
  skip_cleanup: true
  on:
    repo: ararslan/fftw-builder
    tags: true
