language: cpp
sudo: required
dist: trusty
services:
  - docker
matrix:
  include:
    - os: linux
      env: ARCH="x86_64" DOCKER_IMAGE="staticfloat/julia_workerbase:centos6_9-x64" JULIA_URL="https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz"
    - os: osx
      env: ARCH="x86_64" JULIA_URL="https://julialangnightlies-s3.julialang.org/bin/osx/x64/julia-latest-osx.dmg"
      osx_image: xcode8
notifications:
  email: false
before_script:
  - if [ "$(uname)" = "Linux" ]; then
      docker pull $DOCKER_IMAGE;
    fi
  - export CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
  - if [ "$(uname)" = "Linux" ]; then
      mkdir -p ~/julia;
      curl -A "${CURL_USER_AGENT}" -s -L --retry 7 "${JULIA_URL}" | tar -C ~/julia -x -z --strip-components=1 -f -;
    fi
  - if [ "$(uname)" = "Darwin" ]; then
      curl -A "${CURL_USER_AGENT}" -s -L --retry 7 -o julia.dmg "${JULIA_URL}";
      mkdir juliamnt;
      hdiutil mount -readonly -mountpoint juliamnt julia.dmg;
      cp -a juliamnt/*.app/Contents/Resources/julia ~/;
    fi
  - export PATH="${PATH}:${HOME}/julia/bin"
  - julia -e 'versioninfo()'
script:
  - if [ "$(uname)" = "Linux" ]; then
      docker run --user=$(id -u):$(id -g) -ti -v $(pwd):/src -w /src $DOCKER_IMAGE make;
    else
      make;
    fi
  - julia test.jl
before_deploy:
  - tar -cvf libfftw-$(cat VERSION)-$TRAVIS_OS_NAME-$ARCH.tar.gz build/lib/*.*
  - if [ -z "$(ls $TRAVIS_BUILD_DIR/libfftw-*.tar.gz)" ]; then exit 1; fi
deploy:
  provider: releases
  api_key:
    secure: Q6mEIsWWcSWx+LkPr8L73f46Iw0bdXWdi4ELMor/maHbpSEyStNmEx0POHKOKM4/VNketVXie4z7noeLGZURqqoYl28lSSZ1GEs9p2yf8YzhIAwuqkyyVv77pwt2mv8hMbiQBXB3TL8K2yFDzTiUf8QbHFa6Jxuf33Kg3t5q9zTl1Haf2R17ZrqUooeEZNlLJcRvp+PBaTddKxDsWrfxCMdm6mNMn1i3ziq1QVk+VbH5yfYw9guzKAh8DUBe5UzbhwlOdf4mcfzohSWsdzjxVwqhGPXRCCkptcewa/1YQuDlR/FFsUcAjX9MdxBoHuHlJDnz/rC5+8xlw30L1gWXVpjNtklfV4KBUPzfuTfV1QskSYGprtYlO3Q9MIePo7wbl9NkFKvieBXk/BOaW/WLEYsfpzch5zV3X/jSEquwKMr1j1P1YkR3j6InKUzuggm5oDOGS5VLuvArX1HnRcKMj/D89VtVDnD/2tZQYDZVEO88WIcuAAY4pfNjsqxukm5/wOnMzZRNpMSvWDmI+SSe7rNX8dNi7gfgsij1JjsaCp7S6VEn6fF8/HbKumgSjfGyBZjNlm2+WKWxhUw1M+aAs1D6sjtNuD5fr1ykMhxHefQl0+dA4i+fZJifv93ebsOy8W/JUkO3pFiCI1X0GQAfdhgZ44YeY18Esq8TuUPgIdI=
  file_glob: true
  file: "libfftw-*.tar.gz"
  skip_cleanup: true
  on:
    repo: ararslan/fftw-builder
    tags: true
