language: cpp
sudo: false
dist: trusty
matrix:
  include:
    - os: linux
      env: ARCH="i686"
      compiler: "g++-6 -m32"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-6-multilib
            - g++-6-multilib
            - make:i386
    - os: linux
      env: ARCH="x86_64"
      compiler: "g++-6 -m64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
    - os: osx
      env: ARCH="x86_64"
      osx_image: xcode8
branches:
  only:
    - master
notifications:
  email: false
script:
  - make
deploy:
  provider: releases
  api_key:
    secure: "<github oauth token>" # generate with `travis setup releases`
  file_glob: true
  file: $HOME/build/lib/*
  skip_cleanup: true
  on:
    tags: true
