environment:
  matrix:
   - ARCH: "i686"
   - ARCH: "x86_64"
branches:
  only: master
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
clone_depth: 1
init:
  - git config --global core.autocrlf input
build_script:
  - make

# FROM AV DOCS:
# deploy:
#   release: myproduct-v$(appveyor_build_version)
#   description: 'Release description'
#   provider: GitHub
#   auth_token:
#     secure: <your encrypted token> # your encrypted token from GitHub
#   artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#   draft: false
#   prerelease: false
#   on:
#     branch: master                 # release from master branch only
#     appveyor_repo_tag: true        # deploy on tag push only
