version: 2
jobs:
  build:
    docker:
      - image: staticfloat/julia_workerbase:centos6_9-x86
        environment:
          ARCH: i686
    steps:
      - checkout
      - run:
          name: Build FFTW
          command: make
      - run: mkdir /tmp/usr && cp -R build/lib /tmp/usr
      - run:
          name: Compress binaries
          command: |
            TARBALL="libfftw-$(cat VERSION)-linux-i686.tar.gz"
            mkdir -p /tmp/zip
            cd /tmp/usr/lib
            ls -p | grep / | xargs rm -rf
            cd /tmp
            tar -cvzf /tmp/zip/$TARBALL usr
      - store_artifacts:
          path: /tmp/zip
      - persist_to_workspace:
          root: /tmp/usr
          paths:
            - lib
  test:
    docker:
      - image: staticfloat/julia_workerbase:centos6_9-x86
        environment:
          JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/linux/x86/julia-latest-linux32.tar.gz"
    steps:
      - attach_workspace:
          at: /tmp/usr
      - checkout
      - run:
          name: Install x86 Julia nightly
          command: |
            mkdir -p ~/julia
            curl -sL "${JULIA_URL}" | tar -C ~/julia -x -z --strip-components=1 -f -
            ~/julia/bin/julia -e 'versioninfo()'
      - run: mkdir -p build/lib && cp /tmp/usr/lib/*.* build/lib # test code assumes this location
      - run:
          name: Run tests
          command: ~/julia/bin/julia test.jl
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
