version: 2
jobs:
  build:
    docker:
      - image: staticfloat/julia_workerbase:centos6_9-x86
        environment:
          ARCH: i686
          JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/linux/x86/julia-latest-linux32.tar.gz"
    steps:
      - checkout
      - run:
          name: Install x86 Julia nightly
          command: |
            mkdir -p ~/julia
            curl -sL "${JULIA_URL}" | tar -C ~/julia -x -z --strip-components=1 -f -
            ~/julia/bin/julia -e 'versioninfo()'
      - run:
          name: Build FFTW
          command: make
      - run:
          name: Test
          command: ~/julia/bin/julia test.jl
    store_artifacts:
      path: ~/project/build/lib
